name             'firefly_docker'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures firefly_docker'
long_description 'Installs/Configures firefly_docker'
version          '0.1.0'